# Generated by Django 4.2.7 on 2024-01-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probe_agile_data', '0003_rename_scraped_on_city_scraped_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='base',
        ),
    ]
