# Generated by Django 5.0 on 2024-01-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probe_agile_data', '0006_remove_rbi_log_id_alter_rbi_log_sr_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
        migrations.AddField(
            model_name='rbi_log',
            name='data_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rbi_log',
            name='total_record_count',
            field=models.IntegerField(default=0),
        ),
    ]
