# Generated by Django 4.2.7 on 2023-12-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scraping_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('no_of_data_available', models.CharField(default='', max_length=100)),
                ('no_of_data_scraped', models.CharField(default='', max_length=100)),
                ('reason', models.CharField(default='', max_length=100)),
                ('comments', models.CharField(default='', max_length=100)),
                ('trade_date', models.CharField(default='', max_length=100)),
                ('Scraped_new', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'scraping_log',
            },
        ),
    ]
