# Generated by Django 5.0 on 2024-01-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraping_log',
            name='Scraped_new',
        ),
        migrations.AddField(
            model_name='scraping_log',
            name='Scraped_on',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='scraping_log',
            table='scraping_log_bse_nse',
        ),
    ]
