# Generated by Django 4.2.7 on 2024-01-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_remove_scraping_log_scraped_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraping_log',
            name='total_record_count',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterModelTable(
            name='scraping_log',
            table='scraping_log1',
        ),
    ]
