# Generated by Django 5.0 on 2024-01-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_scraping_log_total_record_count_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scraping_log',
            table='scraping_log_bse_nse',
        ),
    ]
